version: "3.8"

networks:
  default:
    external:
      name: backend
services:
  loja-varejo-db:
    image: mongo:latest
    container_name: loja-varejo-db
    ports:
      - 27017:27017
  loja-app-image:
    image: loja-varejo-image
    container_name: loja-varejo-image
    ports:
      - 8080:8080
    links:
      - loja-varejo-db
